development:
  adapter: postgresql
  database: matrizjuridica_development
  encoding: utf8
  gssencmode: disable
  host: <%= ENV.fetch('DATABASE_HOST', '127.0.0.1') %>
  port: <%= ENV.fetch('DATABASE_PORT', 5432) %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  username: <%= ENV.fetch('DATABASE_USERNAME', 'postgres') %>

production:
  adapter: postgresql
  database: matrizjuridica_production
  encoding: utf8
  gssencmode: disable
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV.fetch('DATABASE_PORT', 5432) %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: 100
  username: <%= ENV['DATABASE_USERNAME'] %>

test:
  adapter: postgresql
  database: matrizjuridica_test<%= ENV.fetch('TEST_ENV_NUMBER', '') %>
  encoding: utf8
  gssencmode: disable
  host: <%= ENV.fetch('DATABASE_HOST', '127.0.0.1') %>
  port: <%= ENV.fetch('DATABASE_PORT', 5432) %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  username: <%= ENV.fetch('DATABASE_USERNAME', 'postgres') %>
